@HostAddress = https://localhost:32768
@GameId = c5f73e7d-2dbf-446c-9ed7-71c0094973ba

### Create new game
POST {{HostAddress}}/games/
Accept: application/json
Content-Type: application/json

{
  "level": 0,
  "userName": "Ronny",
  "userId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
}

### Get game
GET {{HostAddress}}/games/{{GameId}}
Accept: application/json

### Update game
PUT {{HostAddress}}/games/{{GameId}}
Accept: application/json
Content-Type: application/json

{
  "row": 0,
  "column": 1,
  "move": 0
}